---
# By default all jobs in one step are executed in parallel and they will be
# all executed even if a failure occurs. It stops after executing all testcases
# part of opnfv/xtesting as the default condition condition to next phase is
# succesful.
# It must be noted that the tests are executed randomly in a step.
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      suites:
        - container: xtesting
          tests:
            - first
            - fail1
            - second
            - third
        - container: xtesting
          repo: ollivier
          tests:
            - fourth
            - fail2
            - fifth
            - sixth
