---
# Here all jobs in one step are executed sequentially and are dropped as soon
# as a failure occurs. Then it continues to the second step here as the
# condition to next phase is always.
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      suites:
        - container: xtesting
          tests:
            - first
            - fail1
            - second
            - third
          properties:
            execution-type: SEQUENTIALLY
            condition: ALWAYS
        - container: xtesting
          repo: ollivier
          tests:
            - fourth
            - fail2
            - fifth
            - sixth
          properties:
            execution-type: SEQUENTIALLY
